name: components_venver
description: Componentes para desenvolvimento de aplicativos Venver
version: 0.0.39
author: Matheus e Nicollas
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0-nullsafety
  # process: ^4.0.0-nullsafety
  path: ^1.7.0
  process: ^4.2.1
  flutter_typeahead: ^3.1.1
  flutter_masked_text: ^0.8.0
  bot_toast: ^4.0.1
  encrypt: ^5.0.0
  pretty_qr_code: ^1.0.1
  cpfcnpj: ^1.0.3
  data_connection_checker: ^0.3.4
  # flutter_svg: ^0.19.3
  # story_view: ^0.13.0-nullsafety.1
  flutter_cache_manager: ^3.0.1
  # uuid: ^3.0.1
  eva_icons_flutter: ^2.0.0
  intl: ^0.17.0
  brasil_fields: ^1.1.1
  mask_text_input_formatter: ^1.2.1
  page_view_indicators: ^2.0.0
  loop_page_view: ^1.0.11
  # masked_text_formatter: ^0.0.1
  # masked_controller: ^1.0.1
  carousel_slider: ^3.0.0
  smooth_page_indicator: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  recase: ^3.0.0
  pedantic: ^1.10.0-nullsafety

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/fonts/fa-solid-900.ttf
          weight: 900
    - family: FontAwesomeLight
      fonts:
        - asset: lib/fonts/fa-light-300.ttf
          weight: 300
    - family: FontAwesomeDuotone
      fonts:
        - asset: lib/fonts/fa-duotone-900.ttf
          weight: 900
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
